apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: phyok
resources:
  - namespace/namespace.yaml
  - configmap/platform-configmap.yaml
  - postgres/postgres.yaml
  - redis/redis.yaml
  - kafka/kafka.yaml
  - qdrant/qdrant.yaml
  - apps/web-services.yaml
  - apps/node-services.yaml
  - apps/java-services.yaml
  - apps/java-autoscaling.yaml
  - apps/java-pdb.yaml
  - ingress/platform-ingress.yaml
