spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:phyok}
    username: ${POSTGRES_USER:phyok}
    password: ${POSTGRES_PASSWORD:change_me_pg}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history_auth
    locations: classpath:db/migration
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.phyok.auth.infrastructure.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
phyok:
  auth:
    audit-enabled: ${PHYOK_AUTH_AUDIT_ENABLED:true}
    audit-base-url: "${AUDIT_INTERNAL_BASE_URL:http://audit-service:18087}"
server:
  port: ${AUTH_PORT:18081}
