apiVersion: v1
kind: ConfigMap
metadata:
  name: phyok-platform-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "phyok"
  POSTGRES_USER: "phyok"
  POSTGRES_PASSWORD: "change_me_pg"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  QDRANT_URL: "http://qdrant:6333"
  NODE2_PORT: "3002"
  CLIENT_BASE_URL: "https://www.phyok.com"
  APP_BASE_URL: "https://www.phyok.com"
  JAVA_DOMAIN_BASE_URL: "http://memory-service:18083"
  JAVA_AUTH_BASE_URL: "http://auth-service:18081"
  JAVA_BILLING_BASE_URL: "http://billing-service:18085"
  JAVA_PAYMENT_BASE_URL: "http://payment-service:18086"
  JAVA_AUDIT_BASE_URL: "http://audit-service:18087"
