spring:
  application:
    name: tenant-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:phyok}
    username: ${POSTGRES_USER:phyok}
    password: ${POSTGRES_PASSWORD:change_me_pg}
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history_tenant
    locations: classpath:db/migration
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.phyok.tenant.infrastructure.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${TENANT_PORT:18082}
